# This tells Nginx (Official Docker Image Handling Frontend & Backend API builds):
# "If the file doesn’t exist, serve index.html so React Router can handle the route."

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.html;
    }
}